name: C++ CI with MinGW-w64
 
on:
   workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup MinGW
      run: choco install mingw -y
    - name: Compile
      run: g++ -finput-charset=utf-8 -fexec-charset=GBK wsltray.cpp -o wsltray.exe -static -lcomctl32 -lshlwapi
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: 'wsltray'
        files: wsltray.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
