name: C++ CI with MinGW-w64
 
on:
   workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup MinGW
      run: choco install mingw -y
    - name: Configure CMake
      run: cmake -B build -G "MinGW Makefiles"
    - name: Build
      run: cmake --build build --config Release
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: 'wsltray'
        files: build/*.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
