name: Android Release
on:
  workflow_dispatch:
jobs:
  build-android:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [arm64]
    steps:
      - uses: actions/checkout@v2
        with:
          path: bililive-go

      - name: Set environment variables
        working-directory: bililive-go
        run: |
          echo "GIT_TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
          echo "ANDROID_NDK_VERSION=r25c" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Install Android NDK
        working-directory: bililive-go
        run: |
          wget https://dl.google.com/android/repository/android-ndk-${{ env.ANDROID_NDK_VERSION }}-linux.zip
          unzip -q android-ndk-${{ env.ANDROID_NDK_VERSION }}-linux.zip
          echo "ANDROID_NDK_ROOT=$(pwd)/android-ndk-${{ env.ANDROID_NDK_VERSION }}" >> $GITHUB_ENV

      - name: Build bililive-go for Android
        working-directory: bililive-go
        run: |
          # 设置交叉编译环境
          if [ "${{ matrix.arch }}" = "arm64" ]; then
            export GOARCH=arm64
            export ANDROID_ARCH=arm64-v8a
          else
            export GOARCH=arm
            export GOARM=7
            export ANDROID_ARCH=armeabi-v7a
          fi

          export GOOS=android
          export CGO_ENABLED=0 # 不需要编译 FFmpeg，禁用 CGO
          export CC=${{ env.ANDROID_NDK_ROOT }}/toolchains/llvm/prebuilt/linux-x86_64/bin/${GOARCH}-linux-android21-clang
          export CXX=${{ env.ANDROID_NDK_ROOT }}/toolchains/llvm/prebuilt/linux-x86_64/bin/${GOARCH}-linux-android21-clang++

          # 编译二进制文件
          mkdir -p bin
          go build -tags release \
            -ldflags "-X github.com/bililive-go/bililive-go/src/consts.AppVersion=${{ env.GIT_TAG }}" \
            -o bin/bililive-go-android-${{ matrix.arch }} \
            ./src/cmd/bililive/

      - name: Upload Android binaries to release
        uses: softprops/action-gh-release@v1
        with:
          files: bililive-go/bin/bililive-go-android-${{ matrix.arch }}
          prerelease: ${{ contains(env.GIT_TAG, 'rc') }}
